services:
  mcp-server:
    image: k33g/sea-flea:demo-wasm-files
    container_name: mcp-server
    ports:
      - "5050:5050"
    environment:
      - MCP_TOKEN=mcp-is-the-way
    command: [
      "--debug",
      "--transport", "streamable-http",
      "--plugins", "./plugins"
    ]
    networks:
      - mcp-network


  initialize:
    build:
      context: ./tests/http.container
      dockerfile_inline: |
        FROM curlimages/curl:latest
        USER root
        # Copy test scripts
        COPY . .
        
        # Make scripts executable
        RUN chmod +x *.sh
        
        
    container_name: test-http-scripts
    networks:
      - mcp-network
    depends_on:
      mcp-server:
        condition: service_started
    environment:
      - MCP_SERVER=http://mcp-server:5050
      - AUTHENTICATION_TOKEN=mcp-is-the-way
    command: |
      sh -c '
      sleep 5
      ./initialize.sh
      '





networks:
  mcp-network:
    driver: bridge

# docker compose --file wasm.compose.yml up